services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OPENAI_API_KEY=${OPENAI_KEY}
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui-data:/app/backend/data
    networks:
      - webui-net
    depends_on:
      - ollama

  ollama:
    build: .
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - webui-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./nginx/certs:/certs
    depends_on:
      - open-webui
    networks:
      - webui-net
networks:
  webui-net:

volumes:
  open-webui-data:
  ollama-data:
